### PR TITLE
Don't add enderpearl cooldown in Creative mode

### PR DESCRIPTION
**Pull request by dentmaged**
Feel free to merge!

### CODE REVIEW

**Comment by jastice** [comment]
Hey, thanks! Do you think you could make it a configurable option?

**Comment by dentmaged** [comment]
@jastice You can't throw enderpearls in creative mode. I don't see why a cool down should be added.

**Comment by jastice** [comment]
Right, forgot about that. Can you tell I haven't been playing a while ;)

**Comment by dentmaged** [comment]
@jastice Maybe support for throwable ender pearls in creative could be implemented soon. I also believe that 1.9 will let players in creative mode throw ender pearls, maybe I could make another PR later to check the version of the server (if I am right in believing that 1.9 will let you pearl in gmc)?

**Comment by jastice** [comment]
I see. A PR in that case would be great, thanks!

**Pull request merged**
